apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
  name: metabase-ingress
  namespace: metabase
spec:
  rules:
    - host: reports.marketingjobverse.com
      http:
        paths:
          - backend:
              service:
                name: metabase
                port:
                  number: 80
            path: /
            pathType: Prefix
