apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: salesjobverse.com
    nginx.ingress.kubernetes.io/proxy-body-size: '50m'
    ingressclass.kubernetes.io/is-default-class: 'true'
  name: salesjobverse-stage-backend-ingress
  namespace: sales-jobverse-stage
spec:
  rules:
    - host: stage-backend.salesjobverse.com
      http:
        paths:
          - backend:
              service:
                name: sales-jobverse-stage-backend
                port:
                  number: 80
            path: /
            pathType: Prefix
  tls: # < placing a host in the TLS config will determine what ends up in the cert's subjectAltNames
    - hosts:
        - stage-backend.salesjobverse.com
      secretName: sales-jobverse-stage-cer