apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    cert-manager.io/cluster-issuer: salesjobverse.com
    ingressclass.kubernetes.io/is-default-class: "true"
  name: sales-jobverse-frontend-ingress
  namespace: sales-jobverse-prod
spec:
  rules:
    - host: salesjobverse.com
      http:
        paths:
          - backend:
              service:
                name: sales-jobverse-frontend
                port:
                  number: 80
            path: /
            pathType: Prefix
    - host: www.salesjobverse.com
      http:
        paths:
          - backend:
              service:
                name: sales-jobverse-frontend
                port:
                  number: 80
            path: /
            pathType: Prefix
  tls: # < placing a host in the TLS config will determine what ends up in the cert's subjectAltNames
    - hosts:
        - salesjobverse.com
        - www.salesjobverse.com
      secretName: prod-sales-jobverse-frontend-cer
