apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    cert-manager.io/cluster-issuer: salesjobverse.com
    ingressclass.kubernetes.io/is-default-class: "true"
  name: sales-jobverse-frontend-stage-ingress
  namespace: sales-jobverse-stage
spec:
  rules:
    - host: stage.salesjobverse.com
      http:
        paths:
          - backend:
              service:
                name: sales-jobverse-frontend-stage
                port:
                  number: 80
            path: /
            pathType: Prefix
  tls: # < placing a host in the TLS config will determine what ends up in the cert's subjectAltNames
    - hosts:
        - stage.salesjobverse.com
      secretName: sales-jobverse-frontend-stage-cer
